### ISSUE TITLE
destinction to nim_lang/sdl2

### ISSUE THREAD

**Issue by krux02** [Vladar4/sdl2_nim#1]
Can you state in the readme, why this wrapper exists, in contrast to the ["official" nim-lang/sdl2 wrapper](https://github.com/nim-lang/sdl2)? I just found out about this repository and the differences I saw so far are the following.

* this wrapper has less commits (whatever that means)
* the examples are ported and actually nice to read
* the event union is actually implemented as a union

I did not yet have time to test it out on my own, but I will. This is not really an issue, because I can see the differences, but it would be nice to have some distinction in the readme.

**Comment by Vladar4** [comment]
Taken care of by 6f4520149a3c39ea81edbff4dd482464d99656bc
