### ISSUE TITLE
Alpha channel not working

### ISSUE THREAD

**Issue by rosshadden** [Vladar4/sdl2_nim#2]
Maybe it's just something I'm doing wrong, but I'm trying to draw two overlapping rectangles with alpha < 255.  I expect to see the first rectangle showing through the second one where they overlap, but instead it is as if alpha is always 255.

Example:

```nim
discard renderer.setRenderDrawColor(Color(r: 0xff, g: 0x00, b: 0x00, a: 0x88))
discard renderer.renderFillRect(rect1)
discard renderer.setRenderDrawColor(Color(r: 0x00, g: 0xff, b: 0x00, a: 0x88))
discard renderer.renderFillRect(rect2)
```

where `rect1` and `rect2` overlap.  I can give a fully complete working example if you need. This is just a general idea.

**Comment by Vladar4** [comment]
Call `discard app.renderer.setRenderDrawBlendMode(sdl.BlendModeBlend)` prior to this.

**Comment by rosshadden** [comment]
Worked great, thanks!
