### ISSUE TITLE
Incorrect reference to x and xlib

### ISSUE THREAD

**Issue by c0ntribut0r** [Vladar4/sdl2_nim#22]
In `sdl_syswm.nim` there is an `import x, xlib` which raises an exception: https://github.com/Vladar4/sdl2_nim/blob/master/sdl2/sdl_syswm.nim#L46

I suppose it should be `import x11/x, x11/xlib`?

**Comment by Vladar4** [comment]
Yep, it seems compatibility was broken in x11 v1.1.
Fixed in aa831b03068c5c3dc71f3971ad0e2c3418af7717
Thanks!
