### ISSUE TITLE
2 requests: the game loop - iOS support ?

### ISSUE THREAD

**Issue by gcmartijn** [Vladar4/sdl2_nim#28]
H!

I'm using nim-lang for the first time, and made a simple test using your SDL 'wrapper'.
At this point everything works oke :) Now it is time to ask some important questions ;)

I don't know if I can ask questions here, but you seem the person that understand those things.

**Multiple Platforms**
Most people want to build to multiple platforms, at the moment I don't even know if it is possible with nim and your SDL 'wrapper'. And how to do that.

It would be nice if you have an example directory iOS/linux/windows with a nim file with "hello world" and a readme.md how to get it working.
That would be super cool, and a go for most people to try/start using nim with your repo.
If your answer is: "This will never run on iOS", than I have to search for another language :(

**The game loop**
Is it possible that you make another frame rate example but this time using the knowledge below.

Many users using the first two links to create a modern game loop, that will run on many devices/systems. This will be the almost perfect starting point for new users and example how to make things work better.

- https://dewitters.com/dewitters-gameloop/
- https://gameprogrammingpatterns.com/game-loop.html
- https://medium.com/@tglaiel/how-to-make-your-game-run-at-60fps-24c61210fe75
- https://www.gamedev.net/blogs/entry/2265460-fixing-your-timestep-and-evaluating-godot/
- http://rbwhitaker.wikidot.com/time-steps
- http://mepem.com/pemcode/?p=50
- https://web.archive.org/web/20170113180149/http://gafferongames.com/game-physics/fix-your-timestep/
- http://www.java-gaming.org/topics/game-loops/24220/view.html

Basically I have something like this
```
fps.nim
import sdl2

const ticksPerSecond = 25
const skipTicks*: float32 = 1000 / ticksPerSecond
const maxFrameSkip* = 5

type Fps* = ref object of RootObj
    nextGameTick*: uint32
    loops*: uint32
    interpolation*: float64

proc init*(this: Fps) =
    this.nextGameTick = sdl2.getTicks()

proc beforeGameUpdateAndEvents*(this: Fps) =
    this.loops = 0

proc afterGameUpdate*(this: Fps) =
    this.interpolation = float64(sdl2.getTicks() + uint32(skipTicks) -
            this.nextGameTick) / float64(skipTicks)
```

```
main.nim
var fps: Fps = Fps()
fps.init()

while app.running:

  fps.beforeGameUpdateAndEvents()

  app.handleEvents()

  while sdl2.getTicks() > fps.nextGameTick and fps.loops < Fps.maxFrameSkip:
    app.update()
    fps.nextGameTick = fps.nextGameTick + uint32(Fps.skipTicks)
    inc(fps.loops)

  fps.afterGameUpdate()

  app.render(fps.interpolation)
```

In the render function I do something like this
```
warning this is old GO language code

	//var drawX int32 = int32((gameobj.x - gameobj.PrevX) * interpolation + gameobj.PrevX);
//	drawX := int32(gameobj.PrevX + interpolation * (gameobj.x - gameobj.PrevX))

// m_Pos_render = m_Pos_previous + ((m_Pos_current - m_Pos_previous) * fInterpolationFraction);
// 	drawX := int32(gameobj.PrevX + ((gameobj.x - gameobj.PrevX) * interpolation))

// state = current_state * alpha + prev_state * (1.0 - alpha);
//	drawX := int32(gameobj.x * interpolation + gameobj.PrevX * (1.0 - interpolation))


//fmt.Printf("interpolation %v\n", (1 * interpolation))
	drawX := int32(gameobj.x + (1 * interpolation))

	//fmt.Printf("X: %v %v\n",
	//	gameobj.PrevX + ((gameobj.x - gameobj.PrevX) * interpolation),
	//	int32(gameobj.PrevX + ((gameobj.x - gameobj.PrevX) * interpolation)),
	//)


	DrawFrame(gameobj.textureId, drawX, int32(gameobj.PrevY), gameobj.width, gameobj.height, gameobj.currentRow, gameobj.currentFrame, pRenderer, sdl.FLIP_NONE)
```

As you can see you don't have to use delta time anymore and use the interpolation.
I'm still testing things, but need a pro that understand those things ;)

Greetings,
GCMartijn

**Comment by Vladar4** [comment]
Greetings!

> Multiple Platforms
> Most people want to build to multiple platforms, at the moment I don't even know if it is possible with nim and your SDL 'wrapper'. And how to do that.
> It would be nice if you have an example directory iOS/linux/windows with a nim file with "hello world" and a readme.md how to get it working.

The code should work on any platform as is, so platform-specific examples are usually unnecessary. It is tested on Linux and Windows, as I have no means to run it on iOS.

> The game loop
> Is it possible that you make another frame rate example but this time using the knowledge below.

There are multiple approaches to the main loop design (you can observe another one in [Nimgame2](https://github.com/Vladar4/nimgame2/blob/master/nimgame2/nimgame.nim#L421), for example), but the purpose of the examples in this repo is to demonstrate and test the abilities of the SDL2 in the most simplistic way, not diving into algorithms too much.

**Comment by gcmartijn** [comment]
Ah oke, I understand. Thanks.

If you ever in the future do a build using nim/sdl on iOS or use the game loop like the example than let me know ;) 

I don't know which game loop I'm going to use after reading all the game loop articles.
