### ISSUE TITLE
Bug drawing Rect

### ISSUE THREAD

**Issue by PrimaIVoid** [Vladar4/sdl2_nim#34]
I noticed in some of the examples and then tested it myself that sometime drawing a Rectangle shows 1 pixel offset in the bottom line of the rectangle,. Only the first or second half of that line seems to be affected though. renderDrawRect produces this bug but FilledRect or other shapes does not

```
   setRenderDrawColor(app.renderer, 0, 99, 99, 0)
    var rect = Rect(x: 10, y: 30, w: 160, h: 60)
    renderDrawRect(app.renderer, addr rect)
```
![rect](https://user-images.githubusercontent.com/62378967/114231055-363d9f00-997a-11eb-806b-b9650f054f37.png)

**Comment by Vladar4** [comment]
Can't reproduce.

Looks like a driver-depended or hardware-compatibility SDL library issue, considering that sdl2_nim just wraps these functions' calls: https://github.com/Vladar4/sdl2_nim/blob/master/sdl2/private/render.nim#L889

**Comment by PrimaIVoid** [comment]
Found this Bug in some other discussions online, even if its rare. I'm not even sure why has not been adressed yet or what may be the cause, but yes, its not related to the bindings but a problem even with original SDL2 libraries, so i'm closing this issue
